apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dpy
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: <insert-image>
          image: app
          ports:
            - containerPort: 80
