name: Publish Image
on:
  push:
    branches:    
      - develop   
jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0      
      - name: Publish Image
        # Uses the master branch of a public repository
        uses: matootie/github-docker@v3.0.0
        with:
          accessToken: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
