name: Publish Image

on:
  push:
    branches:    
      - develop
        -   
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        # Uses the master branch of a public repository
        uses: matootie/github-docker@v3.0.0
        with:
          accessToken: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
